# Generated by Django 5.2.3 on 2025-07-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_chinese', models.CharField(blank=True, max_length=255, verbose_name='Chinese Name')),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('gastroenterology', 'Gastroenterology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('other', 'Other')], max_length=100, verbose_name='Specialization')),
                ('hospital', models.CharField(max_length=255, verbose_name='Hospital')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('experience_years', models.IntegerField(verbose_name='Years of Experience')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('biography_bangla', models.TextField(blank=True, verbose_name='Biography (Bangla)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Photo')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consultation Fee (USD)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('name_bangla', models.CharField(blank=True, max_length=255, verbose_name='Service Name (Bangla)')),
                ('service_type', models.CharField(choices=[('consultation', 'Teleconsultation'), ('second_opinion', 'Second Opinion'), ('treatment', 'Treatment in China'), ('surgery', 'Surgery'), ('diagnostics', 'Diagnostics'), ('medication', 'Medication Access'), ('travel', 'Medical Travel')], max_length=50, verbose_name='Service Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_bangla', models.TextField(blank=True, verbose_name='Description (Bangla)')),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name='Price Range')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Duration')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Patient Name')),
                ('patient_name_bangla', models.CharField(blank=True, max_length=255, verbose_name='Patient Name (Bangla)')),
                ('treatment', models.CharField(max_length=255, verbose_name='Treatment')),
                ('testimonial', models.TextField(verbose_name='Testimonial')),
                ('testimonial_bangla', models.TextField(blank=True, verbose_name='Testimonial (Bangla)')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('teleconsultation', 'Teleconsultation'), ('second_opinion', 'Second Opinion'), ('pre_travel', 'Pre-travel Consultation')], max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('chief_complaint', models.TextField(verbose_name='Chief Complaint')),
                ('medical_documents', models.FileField(blank=True, null=True, upload_to='consultations/', verbose_name='Medical Documents')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescription')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Follow-up Required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_bangla', models.CharField(blank=True, max_length=255, verbose_name='Title (Bangla)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_bangla', models.TextField(blank=True, verbose_name='Content (Bangla)')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Featured Image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('emergency_contact', models.CharField(max_length=255, verbose_name='Emergency Contact')),
                ('medical_history', models.TextField(blank=True, verbose_name='Medical History')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=255, verbose_name='Hospital')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('treatment_type', models.CharField(max_length=255, verbose_name='Treatment Type')),
                ('estimated_duration', models.CharField(max_length=100, verbose_name='Estimated Duration')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated Cost (USD)')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Travel Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('approved', 'Approved'), ('visa_processing', 'Visa Processing'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20, verbose_name='Status')),
                ('visa_assistance', models.BooleanField(default=True, verbose_name='Visa Assistance Required')),
                ('accommodation_assistance', models.BooleanField(default=True, verbose_name='Accommodation Assistance')),
                ('translator_required', models.BooleanField(default=True, verbose_name='Translator Required')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Travel Plan',
                'verbose_name_plural': 'Travel Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
